routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\PostController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\InscriptionController;
use App\Http\Controllers\DeconnexionController;


Route::get('/', function () {
    return view('welcome');
});


Route::resource("post", PostController::class);


Route::middleware("guest")->group(function(){
    // Les routes d'inscription
    Route::get("/register", [InscriptionController::class, "show"]);
    Route::post("/register", [InscriptionController::class, "register"])->name("register");


    Route::get('/login',[AuthController::class,'show'])->name('login.show');
    Route::post('/login',[AuthController::class,'login'])->name('login');
});


Route::middleware("auth")->group(function(){
    Route::post("/logout", [DeconnexionController::class, "logout"])
        ->name("logout");
});

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use App\Models\User;
use App\Models\Tag; 

class Post extends Model
{
    protected $fillable = ['titre', 'contenu', 'user_id'];

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function tags()
    {
        return $this->belongsToMany(Tag::class); 
    }
}

app/Models/Tag.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use App\Post; 

class Tag extends Model
{
    protected $table = 'votre_nom_de_table_tags';
    protected $fillable = ['tag', 'tag_url'];

    public function posts()
    {
        return $this->belongsToMany(Post::class);
    }
}

app/Models/User.php
<?php

namespace App\Models;
use App\Post;
// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;


class User extends Authenticatable
{
    use HasFactory, Notifiable;

    protected $table = 'users';
    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];
    public function posts() 
{ 
return $this->hasMany('App\Post'); 
} 

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * Get the attributes that should be cast.
     *
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'email_verified_at' => 'datetime',
            'password' => 'hashed',
        ];
    }
}

app/Http/Controllers/AuthController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth; 

class AuthController extends Controller
{
    public function show()
    {
        return view('show');
    }

    public function login(Request $request)
    {
        $password=$request->password;
        $email=$request->email;
        $credentials =["email"=>$email ,"password"=>$password];
      

        if (Auth::attempt($credentials)) {
            $request->session()->regenerate();

            return to_route('post.index');
        }

        return back()->withErrors([
            'email' => 'Incorrect email or password.',
        ]);
    }
}

app/Http/Controllers/CommandeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class CommandeController extends Controller
{
    //
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

abstract class Controller
{
    //
}

app/Http/Controllers/DeconnexionController.php
<?php

namespace App\Http\Controllers;
use Illuminate\Support\Facades\Auth;
use Illuminate\Http\Request;

class DeconnexionController extends Controller
{
   
    public function logout(Request $request)
    {
        Auth::logout(); 
        $request->session()->invalidate(); 
        $request->session()->regenerateToken(); 

        return redirect('/'); 
    }
    }
    

app/Http/Controllers/InscriptionController.php
<?php

namespace App\Http\Controllers;
use App\Models\User; // Import de la classe User
use Illuminate\Support\Facades\Hash;
use Illuminate\Http\Request;

class InscriptionController extends Controller
{

    
        public function show(){
            return view ("register");
        }



        public function register(Request $request)
{
    $request->validate([
        'name' => 'required|string|max:255',
        'email' => 'required|string|email|max:255|unique:users',
        'password' => 'required|string|min:8|confirmed',
    ]);

 
    $user = User::create([
        'name' => $request->name,
        'email' => $request->email,
        'password' => Hash::make($request->password),
    ]);


    return redirect()->route('login')->with('success', 'Inscription réussie ! Bienvenue !');
}

}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;


use App\Models\Post;
use App\Http\Requests\PostRequest;
use Illuminate\Http\Request;

class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $posts = Post::latest()->paginate(2);
        return view('posts.index', compact('posts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('posts.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\PostRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'titre' => 'required|string|max:80',
            'contenu' => 'required',
        ]);

        
        $post = Post::create([
            'titre' => $request->titre,
            'contenu' => $request->contenu,
            'user_id' => auth()->id(),
        ]);

        return redirect()->route('post.index')->with('success', 'Post créé avec succès.');
    }


    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function show(Post $post)
    {
        return view('posts.show', compact('post'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function edit(Post $post)
    {
        return view('posts.edit', compact('post'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\Requests\PostRequest  $request
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function update(PostRequest $request, Post $post)
    {
        $post->update($request->validated());

        return redirect()->route('posts.index')->with('success', 'Post updated successfully.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function destroy(Post $post , Request $request)
{
    // Vérifiez si l'utilisateur peut supprimer le post
    // if (Request->user()->can('delete', $post)) {
    //     abort(403);
    // }

    // Supprimer le post
    $post->delete();

    return redirect()->back(); 
}



    // public function indexTag($tagUrl)
    // {
      
    //     $tag = Tag::where('tag_url', $tagUrl)->first();

    //     if ($tag) {
         
    //         $posts = Post::whereHas('tags', function ($query) use ($tag) {
    //             $query->where('tag_id', $tag->id);
    //         })->paginate(10);

         
    //         return view('posts.tagged', compact('posts', 'tag'));
    //     } else {
           
    //         return redirect()->route('post.index')->with('error', 'Aucun article trouvé pour ce tag.');
    //     }
    // }




    // <div class="pull-right">
    //                         @foreach($post->tags as $tag)
    //                         <a href="{{ url('post/tag/' . $tag->tag_url) }}" class="btn btn-xs btn-info">{{ $tag->tag }}</a>
    //                         @endforeach
    //                     </div> 
}

resources/views/posts/create.blade.php
@extends('template')

@section('contenu')
<div class="container">
    <div class="row">
        <div class="col-md-offset-3 col-md-6">
            <div class="panel panel-info">
                <div class="panel-heading">Ajout d'un article</div>
                <div class="panel-body">
                    <form action="{{ route('post.store') }}" method="POST">
                        @csrf
                        <div class="form-group {{ $errors->has('titre') ? 'has-error' : '' }}">
                            <input type="text" name="titre" class="form-control" placeholder="Titre">
                            @if ($errors->has('titre'))
                                <small class="text-danger">{{ $errors->first('titre') }}</small>
                            @endif
                        </div>
                        <div class="form-group {{ $errors->has('contenu') ? 'has-error' : '' }}">
                            <textarea name="contenu" class="form-control" placeholder="Contenu"></textarea>
                            @if ($errors->has('contenu'))
                                <small class="text-danger">{{ $errors->first('contenu') }}</small>
                            @endif
                        </div>
                        <div class="form-group">
                            <label for="tags">Mots-clés (séparés par des virgules):</label>
                            <input type="text" class="form-control" id="tags" name="tags" placeholder="Entrez les mots-clés">
                            @error('tags')
                            <small class="text-danger">{{ $message }}</small>
                            @enderror
                        </div>
                        <button type="submit" class="btn btn-info pull-right">Envoyer !</button>
                    </form>
                </div>
            </div>
            <a href="{{ url()->previous() }}" class="btn btn-primary">
                <span class="glyphicon glyphicon-circle-arrow-left"></span> Retour
            </a>
        </div>
    </div>
</div>
@endsection

resources/views/posts/index.blade.php
@extends('template')

@section('header')
@auth

    <div class="btn-group pull-right">
        <a href="{{ route('post.create') }}" class="btn btn-info">Créer un article</a>
        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: inline;">
            @csrf
            <button type="submit" class="btn btn-warning">Déconnexion</button>
        </form>
    </div>
@endauth

@guest
    <a href="{{ url('login') }}" class="btn btn-info pull-right">Se connecter</a>
    <a href="{{ route('register') }}" class="btn btn-info pull-right">S'inscrire</a>
@endguest
@endsection

@section('contenu')
@if(isset($info))
    <div class="row alert alert-info">{{ $info }}</div>
@endif

<div class="d-flex">
        {{ $posts->links() }}
    </div>


@foreach($posts as $post)
    <article class="row bg-primary">
        <div class="col-md-12">
            <header>
                <h1>{{ $post->titre }}</h1>
            </header>
            <hr>
            <section>
                <p>{{ $post->contenu }}</p>
          
             @auth
                    <form method="POST" action="{{ route('post.destroy', $post->id) }}">
                        @csrf
                        @method('DELETE')
                        <button type="submit" class="btn btn-danger">Supprimer cet article</button>
                    </form>
            @endauth
            
                <em class="pull-right">
                    <span class="glyphicon glyphicon-pencil"></span>
                    {{ $post->user->name }} le {{ $post->created_at->format('d-m-Y') }}
                </em>
            </section>
        </div>
    </article>
    <br>
@endforeach
@endsection

resources/views/register.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Inscription</title>
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>

@if(session('success'))
    <div class="alert alert-success">
        {{ session('success') }}
    </div>
@endif

<div class="container py-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card shadow">
                <div class="card-header bg-primary text-white text-center">
                    <h3 class="mb-0">Inscription</h3>
                </div>
                <div class="card-body">
                    <form method="POST" action="{{ route('register') }}">
                        @csrf
                        <div class="form-group">
                            <label for="name">Nom</label>
                            <input type="text" class="form-control" id="name" name="name" placeholder="Entrez votre nom" >
                            @error('name')
                                <span class="text-danger">{{ $message }}</span>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="email">Adresse e-mail</label>
                            <input type="email" class="form-control" id="email" name="email" placeholder="Entrez votre adresse e-mail" >
                            @error('email')
                                <span class="text-danger">{{ $message }}</span>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="password">Mot de passe</label>
                            <input type="password" class="form-control" id="password" name="password" placeholder="Entrez votre mot de passe" >
                            @error('password')
                                <span class="text-danger">{{ $message }}</span>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="password_confirmation">Confirmation du mot de passe</label>
                            <input type="password" class="form-control" id="password_confirmation" name="password_confirmation" placeholder="Confirmez votre mot de passe" >
                        </div>
                        <button type="submit" class="btn btn-primary btn-block">S'inscrire</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<script src="{{ asset('js/app.js') }}"></script>
</

resources/views/show.blade.php
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
    <div class="container py-5">
        <div class="row">
            <div class="col-md-6 mx-auto">
                <h1 class="h2 text-center mb-4">Se connecter</h1>
                <form method="POST" action="{{ route('login') }}" class="needs-validation" novalidate>
                    @csrf
                    <div class="form-group">
                        <label for="email">Adresse e-mail</label>
                        <input type="email" class="form-control" id="email" name="email" placeholder="Entrez votre adresse e-mail" required>
                        <div class="invalid-feedback">
                            Veuillez entrer une adresse e-mail valide.
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="password">Mot de passe</label>
                        <input type="password" class="form-control" id="password" name="password" placeholder="Entrez votre mot de passe" required>
                        <div class="invalid-feedback">
                            Veuillez entrer votre mot de passe.
                        </div>
                    </div>
                    <button type="submit" class="btn btn-primary btn-block">Se connecter</button>
                </form>
            </div>
        </div>
    </div>
    <script src="{{ asset('js/app.js') }}"></script>
</body>
</html>

resources/views/template.blade.php
<!DOCTYPE html> 
<html lang="fr"> 
  <head> 
    <meta charset="utf-8"> 
    <meta http-equiv="X-UA-Compatible" content="IE=edge"> 
    <meta name="viewport" content="width=device-width, initial-scale=1"> 
    <title>Mon joli site</title> 
    <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"> 
    <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css"> 

    <style>textarea{resize:none;}</style> 
  </head> 
  <body> 
    <header class="jumbotron"> 
      <div class="container"> 
        <h1 class="page-header"><a href="{{ route('post.index') }}">Mon joli blog</a></h1> 
        @yield('header') 
      </div> 
    </header> 
    <div class="container"> 
      @yield('contenu') 
    </div> 
  
  </body> 
</html>